import 'dart:io';

import 'package:path/path.dart' as p;

import '../config.dart';
import '../log.dart';
import '../process_runner.dart';
import 'api_url_sync.dart';

/// Writes [CodemagicConfig.path] for Serverpod monorepos (Flutter iOS/Android).
///
/// Does **not** trigger builds or manage signing — generate config only.
/// Trigger via Codemagic dashboard or REST API (`POST /builds`).
///
/// On each deploy: create file if missing; if present, **sync** `SERVER_URL`
/// (or [WebConfig.serverUrlDefine]) from [WebConfig.apiUrl] without rewriting
/// the rest of the file.
class CodemagicYamlWriter {
  CodemagicYamlWriter({
    required this.config,
    required this.runner,
    required this.log,
  });

  final PodflyConfig config;
  final ProcessRunner runner;
  final Log log;

  /// When [mobile.provider] is codemagic and [writeYaml] is true, write
  /// `codemagic.yaml` if missing; always sync API URL when the file exists.
  Future<void> ensure() async {
    if (config.mobile.provider != MobileProvider.codemagic) return;
    final cm = config.mobile.codemagicOrDefault;
    if (!cm.writeYaml) {
      log.detail('mobile.codemagic.write_yaml: false — skip codemagic.yaml');
      return;
    }
    if (!cm.ios && !cm.android) {
      log.warn('mobile.codemagic: ios and android both false — nothing to write');
      return;
    }

    final path = p.join(config.root, cm.path);
    if (await File(path).exists()) {
      await _syncApiUrl(path);
      return;
    }

    final body = generateYaml(config);
    if (runner.dryRun) {
      log.dry('write $path (${body.length} bytes)');
      return;
    }
    await File(path).writeAsString(body);
    log.ok('wrote ${p.relative(path, from: config.root)} '
        '(Codemagic iOS/Android — connect repo + signing in dashboard)');
  }

  Future<void> _syncApiUrl(String path) async {
    final rel = p.relative(path, from: config.root);
    final raw = await File(path).readAsString();
    final result = MobileApiUrlSync.apply(
      raw,
      defineName: config.web.serverUrlDefine,
      apiUrl: config.web.apiUrlNormalized,
    );
    if (!result.changed) {
      log.detail(
        '$rel — API URL already '
        '${MobileApiUrlSync.apiForDefine(config.web.apiUrlNormalized)}',
      );
      return;
    }
    if (runner.dryRun) {
      log.dry('sync API URL in $rel (${result.replacements} site(s))');
      return;
    }
    await File(path).writeAsString(result.text);
    log.ok(
      'synced ${config.web.serverUrlDefine} → '
      '${MobileApiUrlSync.apiForDefine(config.web.apiUrlNormalized)} in $rel '
      '(${result.replacements} site(s))',
    );
  }

  /// Pure generator for tests / force-regenerate tooling.
  static String generateYaml(PodflyConfig config) {
    final cm = config.mobile.codemagicOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final apiUrl = config.web.apiUrlNormalized;
    // Codemagic vars prefer no trailing slash for many clients; keep as configured.
    final apiForDefine = apiUrl.endsWith('/') && apiUrl.length > 8
        ? apiUrl.substring(0, apiUrl.length - 1)
        : apiUrl;
    final instance = cm.instanceType;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — Codemagic mobile CI for Serverpod monorepo.');
    buf.writeln('#');
    buf.writeln('# API is deployed separately: podfly deploy --api');
    buf.writeln('# This file only builds Flutter iOS/Android against that API URL.');
    buf.writeln('#');
    buf.writeln('# Setup:');
    buf.writeln('#   1. Push this repo and add it in https://codemagic.io');
    buf.writeln('#   2. Add signing (iOS distribution + Play service account)');
    buf.writeln('#   3. Run workflow ios-ipa / android-appbundle from the UI');
    buf.writeln('#      or: POST https://api.codemagic.io/builds  (x-auth-token)');
    buf.writeln('#');
    buf.writeln('# Structure is left alone after create; each deploy re-syncs');
    buf.writeln('# $define lines marked # ${MobileApiUrlSync.marker} from web.api_url.');
    buf.writeln('#');
    buf.writeln('# Docs: https://docs.codemagic.io/flutter-configuration/flutter-projects/');
    buf.writeln('#       https://github.com/127thousand/podfly/blob/main/doc/codemagic.md');
    buf.writeln();
    buf.writeln('workflows:');

    if (cm.ios) {
      _writeIosWorkflow(
        buf,
        flutterRel: flutterRel,
        define: define,
        apiUrl: apiForDefine,
        instance: instance,
        cm: cm,
      );
    }
    if (cm.android) {
      _writeAndroidWorkflow(
        buf,
        flutterRel: flutterRel,
        define: define,
        apiUrl: apiForDefine,
        instance: instance,
        cm: cm,
      );
    }
    return buf.toString();
  }

  static void _writeIosWorkflow(
    StringBuffer buf, {
    required String flutterRel,
    required String define,
    required String apiUrl,
    required String instance,
    required CodemagicConfig cm,
  }) {
    final hasAsc = cm.appStoreConnectIntegration != null &&
        cm.appStoreConnectIntegration!.isNotEmpty;
    final bundle = cm.bundleId ?? 'com.example.app';

    buf.writeln('  ios-ipa:');
    buf.writeln('    name: iOS IPA');
    buf.writeln('    max_build_duration: 60');
    buf.writeln('    instance_type: $instance');
    buf.writeln();
    if (hasAsc) {
      buf.writeln('    integrations:');
      buf.writeln('      app_store_connect: ${cm.appStoreConnectIntegration}');
      buf.writeln();
    } else {
      buf.writeln('    # integrations:');
      buf.writeln('    #   app_store_connect: <name from Teams → Integrations>');
      buf.writeln();
    }
    buf.writeln('    environment:');
    buf.writeln('      # Create group "ios_signing" in Codemagic for CERTIFICATE_PRIVATE_KEY etc.');
    buf.writeln('      groups:');
    buf.writeln('        - ios_signing');
    buf.writeln('      flutter: stable');
    buf.writeln('      xcode: latest');
    buf.writeln('      cocoapods: default');
    buf.writeln('      vars:');
    buf.writeln('        BUNDLE_ID: $bundle');
    buf.writeln(
        '        $define: $apiUrl  # ${MobileApiUrlSync.marker}');
    if (cm.appId != null) {
      buf.writeln('        # CODEMAGIC_APP_ID: ${cm.appId}');
    }
    buf.writeln();
    buf.writeln('    cache:');
    buf.writeln('      cache_paths:');
    buf.writeln('        - \$HOME/.pub-cache');
    buf.writeln('        - \$CM_BUILD_DIR/$flutterRel/ios/Pods');
    buf.writeln();
    buf.writeln('    scripts:');
    buf.writeln('      - name: Get Flutter packages');
    buf.writeln('        script: |');
    buf.writeln('          cd $flutterRel');
    buf.writeln('          flutter pub get');
    buf.writeln('      - name: Install CocoaPods dependencies');
    buf.writeln('        script: |');
    buf.writeln('          cd $flutterRel/ios');
    buf.writeln('          pod install');
    buf.writeln('      - name: Set up code signing settings on Xcode project');
    buf.writeln('        script: |');
    buf.writeln('          # Requires Codemagic CLI tools (preinstalled on CM Macs)');
    buf.writeln('          # and ios_signing group. See doc/codemagic.md.');
    buf.writeln('          xcode-project use-profiles || true');
    buf.writeln('      - name: Flutter build ipa');
    buf.writeln('        script: |');
    buf.writeln('          cd $flutterRel');
    buf.writeln('          flutter build ipa --release \\');
    buf.writeln('            --dart-define=$define=\$$define \\');
    buf.writeln('            --export-options-plist=/Users/builder/export_options.plist \\');
    buf.writeln('            || flutter build ipa --release \\');
    buf.writeln('              --dart-define=$define=\$$define');
    buf.writeln();
    buf.writeln('    artifacts:');
    buf.writeln('      - $flutterRel/build/ios/ipa/*.ipa');
    buf.writeln('      - /tmp/xcodebuild_logs/*.log');
    buf.writeln();
    if (cm.publishTestflight && hasAsc) {
      buf.writeln('    publishing:');
      buf.writeln('      app_store_connect:');
      buf.writeln('        auth: integration');
      buf.writeln('        submit_to_testflight: true');
    } else {
      buf.writeln('    # publishing:');
      buf.writeln('    #   app_store_connect:');
      buf.writeln('    #     auth: integration');
      buf.writeln('    #     submit_to_testflight: true');
      buf.writeln('    # Set mobile.codemagic.publish_testflight: true + app_store_connect in podfly.yaml');
    }
    buf.writeln();
  }

  static void _writeAndroidWorkflow(
    StringBuffer buf, {
    required String flutterRel,
    required String define,
    required String apiUrl,
    required String instance,
    required CodemagicConfig cm,
  }) {
    final package = cm.androidPackageName ?? 'com.example.app';

    buf.writeln('  android-appbundle:');
    buf.writeln('    name: Android App Bundle');
    buf.writeln('    max_build_duration: 60');
    buf.writeln('    instance_type: $instance');
    buf.writeln();
    buf.writeln('    environment:');
    buf.writeln('      # Create group "android_signing" with CM_KEYSTORE / passwords.');
    buf.writeln('      groups:');
    buf.writeln('        - android_signing');
    buf.writeln('      flutter: stable');
    buf.writeln('      vars:');
    buf.writeln('        PACKAGE_NAME: $package');
    buf.writeln(
        '        $define: $apiUrl  # ${MobileApiUrlSync.marker}');
    buf.writeln();
    buf.writeln('    cache:');
    buf.writeln('      cache_paths:');
    buf.writeln('        - \$HOME/.pub-cache');
    buf.writeln();
    buf.writeln('    scripts:');
    buf.writeln('      - name: Set up local.properties');
    buf.writeln('        script: |');
    buf.writeln('          echo "flutter.sdk=\$HOME/programs/flutter" > "\$CM_BUILD_DIR/$flutterRel/android/local.properties"');
    buf.writeln('      - name: Get Flutter packages');
    buf.writeln('        script: |');
    buf.writeln('          cd $flutterRel');
    buf.writeln('          flutter pub get');
    buf.writeln('      - name: Flutter build appbundle');
    buf.writeln('        script: |');
    buf.writeln('          cd $flutterRel');
    buf.writeln('          flutter build appbundle --release \\');
    buf.writeln('            --dart-define=$define=\$$define');
    buf.writeln();
    buf.writeln('    artifacts:');
    buf.writeln('      - $flutterRel/build/app/outputs/**/*.aab');
    buf.writeln();
    if (cm.publishPlay) {
      buf.writeln('    publishing:');
      buf.writeln('      google_play:');
      buf.writeln('        # credentials: \$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS');
      buf.writeln('        track: internal');
      buf.writeln('        submit_as_draft: true');
    } else {
      buf.writeln('    # publishing:');
      buf.writeln('    #   google_play:');
      buf.writeln('    #     credentials: \$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS');
      buf.writeln('    #     track: internal');
      buf.writeln('    # Set mobile.codemagic.publish_play: true when ready');
    }
    buf.writeln();
  }
}
