import 'dart:io';

import 'package:path/path.dart' as p;

import '../config.dart';
import '../log.dart';
import '../process_runner.dart';

/// Writes GitHub Actions workflows for Flutter iOS/Android builds.
///
/// Same idea as [CodemagicYamlWriter]: generate pipeline files only.
/// Builds run on push / `workflow_dispatch` in GitHub — not via a podfly CLI.
class GithubActionsMobileWriter {
  GithubActionsMobileWriter({
    required this.config,
    required this.runner,
    required this.log,
  });

  final PodflyConfig config;
  final ProcessRunner runner;
  final Log log;

  Future<void> ensure() async {
    if (config.mobile.provider != MobileProvider.githubActions) return;
    final g = config.mobile.githubActionsOrDefault;
    if (!g.writeYaml) {
      log.detail(
          'mobile.github_actions.write_yaml: false — skip workflow files');
      return;
    }
    if (!g.ios && !g.android) {
      log.warn(
          'mobile.github_actions: ios and android both false — nothing to write');
      return;
    }

    final dir = p.join(config.root, g.workflowsDir);
    if (g.android) {
      await _writeIfMissing(
        p.join(dir, g.androidWorkflow),
        generateAndroidWorkflow(config),
      );
    }
    if (g.ios) {
      await _writeIfMissing(
        p.join(dir, g.iosWorkflow),
        generateIosWorkflow(config),
      );
    }
  }

  Future<void> _writeIfMissing(String path, String body) async {
    final rel = p.relative(path, from: config.root);
    if (await File(path).exists()) {
      log.detail('$rel already present — leaving in place');
      return;
    }
    if (runner.dryRun) {
      log.dry('write $path (${body.length} bytes)');
      return;
    }
    await File(path).parent.create(recursive: true);
    await File(path).writeAsString(body);
    log.ok('wrote $rel (GitHub Actions mobile — secrets in repo Settings)');
  }

  static String _apiForDefine(PodflyConfig config) {
    final apiUrl = config.web.apiUrlNormalized;
    if (apiUrl.endsWith('/') && apiUrl.length > 8) {
      return apiUrl.substring(0, apiUrl.length - 1);
    }
    return apiUrl;
  }

  /// Android App Bundle workflow (ubuntu).
  static String generateAndroidWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final api = _apiForDefine(config);
    final channel = g.flutterChannel;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — Flutter Android CI for Serverpod monorepo.');
    buf.writeln('#');
    buf.writeln('# API is deployed separately: podfly deploy --api');
    buf.writeln('# (see deploy.yml). This workflow only builds the mobile client.');
    buf.writeln('#');
    buf.writeln('# Signing (optional): add keystore secrets and uncomment the');
    buf.writeln('# signing steps. Default is an unsigned/debug-keystore release');
    buf.writeln('# build artifact for CI validation.');
    buf.writeln('#');
    buf.writeln('# podfly does not overwrite this file once it exists.');
    buf.writeln('# Sync SERVER_URL with web.api_url in podfly.yaml when the API host changes.');
    buf.writeln('#');
    buf.writeln('# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md');
    buf.writeln();
    buf.writeln('name: Mobile Android');
    buf.writeln();
    buf.writeln('on:');
    buf.writeln('  workflow_dispatch:');
    buf.writeln('  push:');
    buf.writeln('    branches: [main]');
    buf.writeln('    paths:');
    buf.writeln('      - \'$flutterRel/**\'');
    buf.writeln('      - \'.github/workflows/${g.androidWorkflow}\'');
    buf.writeln();
    buf.writeln('concurrency:');
    buf.writeln('  group: mobile-android-\${{ github.ref }}');
    buf.writeln('  cancel-in-progress: true');
    buf.writeln();
    buf.writeln('jobs:');
    buf.writeln('  appbundle:');
    buf.writeln('    name: flutter build appbundle');
    buf.writeln('    runs-on: ubuntu-latest');
    buf.writeln('    timeout-minutes: 45');
    buf.writeln('    permissions:');
    buf.writeln('      contents: read');
    buf.writeln();
    buf.writeln('    defaults:');
    buf.writeln('      run:');
    buf.writeln('        working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('    steps:');
    buf.writeln('      - name: Checkout');
    buf.writeln('        uses: actions/checkout@v4');
    buf.writeln();
    buf.writeln('      - name: Set up Java');
    buf.writeln('        uses: actions/setup-java@v4');
    buf.writeln('        with:');
    buf.writeln('          distribution: temurin');
    buf.writeln('          java-version: \'17\'');
    buf.writeln();
    buf.writeln('      - name: Set up Flutter');
    buf.writeln('        uses: subosito/flutter-action@v2');
    buf.writeln('        with:');
    buf.writeln('          channel: $channel');
    buf.writeln('          cache: true');
    buf.writeln();
    buf.writeln('      - name: Flutter pub get');
    buf.writeln('        run: flutter pub get');
    buf.writeln();
    buf.writeln('      - name: Build App Bundle');
    buf.writeln('        run: |');
    buf.writeln('          flutter build appbundle --release \\');
    buf.writeln('            --dart-define=$define=$api');
    buf.writeln();
    buf.writeln('      - name: Upload AAB');
    buf.writeln('        uses: actions/upload-artifact@v4');
    buf.writeln('        with:');
    buf.writeln('          name: app-release-aab');
    buf.writeln('          path: $flutterRel/build/app/outputs/**/*.aab');
    buf.writeln('          if-no-files-found: error');
    buf.writeln();
    return buf.toString();
  }

  /// iOS IPA workflow (macos). Default build is unsigned (`--no-codesign`)
  /// so CI validates compile; enable signing with repo secrets.
  static String generateIosWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final api = _apiForDefine(config);
    final channel = g.flutterChannel;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — Flutter iOS CI for Serverpod monorepo.');
    buf.writeln('#');
    buf.writeln('# API is deployed separately: podfly deploy --api');
    buf.writeln('#');
    buf.writeln('# Default: `flutter build ios --no-codesign` (compile check +');
    buf.writeln('# artifact). For TestFlight, add signing secrets and switch to');
    buf.writeln('# `flutter build ipa` (see comments in the build step).');
    buf.writeln('#');
    buf.writeln('# macos runners are billed minutes — prefer workflow_dispatch');
    buf.writeln('# for day-to-day; push paths filter limits automatic runs.');
    buf.writeln('#');
    buf.writeln('# podfly does not overwrite this file once it exists.');
    buf.writeln('#');
    buf.writeln('# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md');
    buf.writeln();
    buf.writeln('name: Mobile iOS');
    buf.writeln();
    buf.writeln('on:');
    buf.writeln('  workflow_dispatch:');
    buf.writeln('  push:');
    buf.writeln('    branches: [main]');
    buf.writeln('    paths:');
    buf.writeln('      - \'$flutterRel/**\'');
    buf.writeln('      - \'.github/workflows/${g.iosWorkflow}\'');
    buf.writeln();
    buf.writeln('concurrency:');
    buf.writeln('  group: mobile-ios-\${{ github.ref }}');
    buf.writeln('  cancel-in-progress: true');
    buf.writeln();
    buf.writeln('jobs:');
    buf.writeln('  ios:');
    buf.writeln('    name: flutter build ios');
    buf.writeln('    runs-on: macos-latest');
    buf.writeln('    timeout-minutes: 60');
    buf.writeln('    permissions:');
    buf.writeln('      contents: read');
    buf.writeln();
    buf.writeln('    defaults:');
    buf.writeln('      run:');
    buf.writeln('        working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('    steps:');
    buf.writeln('      - name: Checkout');
    buf.writeln('        uses: actions/checkout@v4');
    buf.writeln();
    buf.writeln('      - name: Set up Flutter');
    buf.writeln('        uses: subosito/flutter-action@v2');
    buf.writeln('        with:');
    buf.writeln('          channel: $channel');
    buf.writeln('          cache: true');
    buf.writeln();
    buf.writeln('      - name: Flutter pub get');
    buf.writeln('        run: flutter pub get');
    buf.writeln();
    buf.writeln('      - name: CocoaPods');
    buf.writeln('        run: |');
    buf.writeln('          cd ios');
    buf.writeln('          pod install');
    buf.writeln();
    buf.writeln('      - name: Build iOS (no codesign)');
    buf.writeln('        run: |');
    buf.writeln('          # Unsigned compile check. For store IPA + TestFlight:');
    buf.writeln('          #   - import certs/profiles via secrets');
    buf.writeln('          #   - flutter build ipa --release --dart-define=$define=$api');
    buf.writeln('          flutter build ios --release --no-codesign \\');
    buf.writeln('            --dart-define=$define=$api');
    buf.writeln();
    buf.writeln('      - name: Upload build (optional)');
    buf.writeln('        if: success()');
    buf.writeln('        uses: actions/upload-artifact@v4');
    buf.writeln('        with:');
    buf.writeln('          name: ios-release-unsigned');
    buf.writeln('          path: $flutterRel/build/ios/iphoneos');
    buf.writeln('          if-no-files-found: warn');
    buf.writeln();
    return buf.toString();
  }
}
