import 'dart:io';

import 'package:path/path.dart' as p;

import '../config.dart';
import '../log.dart';
import '../process_runner.dart';
import 'api_url_sync.dart';

/// Writes GitHub Actions workflows (+ optional Fastlane) for Flutter mobile.
///
/// Generate pipeline files only — builds run on push / `workflow_dispatch`.
/// With [GithubActionsMobileConfig.fastlane], scaffolds Fastlane under the
/// Flutter package and workflows call `bundle exec fastlane`.
///
/// On each deploy: create missing files; if a workflow already exists, **sync**
/// `SERVER_URL` / dart-define URLs from [WebConfig.apiUrl] without clobbering
/// the rest of the file.
class GithubActionsMobileWriter {
  GithubActionsMobileWriter({
    required this.config,
    required this.runner,
    required this.log,
  });

  final PodflyConfig config;
  final ProcessRunner runner;
  final Log log;

  Future<void> ensure() async {
    if (config.mobile.provider != MobileProvider.githubActions) return;
    final g = config.mobile.githubActionsOrDefault;
    if (!g.writeYaml) {
      log.detail(
          'mobile.github_actions.write_yaml: false — skip workflow files');
      return;
    }
    if (!g.ios && !g.android) {
      log.warn(
          'mobile.github_actions: ios and android both false — nothing to write');
      return;
    }

    if (g.fastlane) {
      await _ensureFastlane();
    }

    final dir = p.join(config.root, g.workflowsDir);
    if (g.android) {
      await _writeOrSyncApiUrl(
        p.join(dir, g.androidWorkflow),
        generateAndroidWorkflow(config),
        hint: g.fastlane
            ? 'GHA + Fastlane android'
            : 'GHA Android compile',
      );
    }
    if (g.ios) {
      await _writeOrSyncApiUrl(
        p.join(dir, g.iosWorkflow),
        generateIosWorkflow(config),
        hint: g.fastlane ? 'GHA + Fastlane ios' : 'GHA iOS compile',
      );
    }
  }

  Future<void> _ensureFastlane() async {
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final base = p.join(config.root, flutterRel);
    final fastlaneDir = p.join(base, 'fastlane');

    // Fastfile reads SERVER_URL from ENV — no URL hardcode to sync.
    await _writeIfMissing(
      p.join(base, 'Gemfile'),
      generateGemfile(),
      hint: 'Fastlane Gemfile',
    );
    await _writeIfMissing(
      p.join(fastlaneDir, 'Fastfile'),
      generateFastfile(config),
      hint: 'Fastlane Fastfile',
    );
    await _writeIfMissing(
      p.join(fastlaneDir, 'Appfile'),
      generateAppfile(config),
      hint: 'Fastlane Appfile',
    );
    await _writeIfMissing(
      p.join(fastlaneDir, 'Matchfile'),
      generateMatchfile(config),
      hint: 'Fastlane Matchfile (stub)',
    );
  }

  Future<void> _writeOrSyncApiUrl(
    String path,
    String body, {
    required String hint,
  }) async {
    final rel = p.relative(path, from: config.root);
    if (await File(path).exists()) {
      await _syncApiUrl(path);
      return;
    }
    if (runner.dryRun) {
      log.dry('write $path (${body.length} bytes)');
      return;
    }
    await File(path).parent.create(recursive: true);
    await File(path).writeAsString(body);
    log.ok('wrote $rel ($hint — secrets in repo Settings)');
  }

  Future<void> _writeIfMissing(
    String path,
    String body, {
    String hint = 'GitHub Actions mobile',
  }) async {
    final rel = p.relative(path, from: config.root);
    if (await File(path).exists()) {
      log.detail('$rel already present — leaving in place');
      return;
    }
    if (runner.dryRun) {
      log.dry('write $path (${body.length} bytes)');
      return;
    }
    await File(path).parent.create(recursive: true);
    await File(path).writeAsString(body);
    log.ok('wrote $rel ($hint — secrets in repo Settings)');
  }

  Future<void> _syncApiUrl(String path) async {
    final rel = p.relative(path, from: config.root);
    final raw = await File(path).readAsString();
    final result = MobileApiUrlSync.apply(
      raw,
      defineName: config.web.serverUrlDefine,
      apiUrl: config.web.apiUrlNormalized,
    );
    if (!result.changed) {
      log.detail(
        '$rel — API URL already '
        '${MobileApiUrlSync.apiForDefine(config.web.apiUrlNormalized)}',
      );
      return;
    }
    if (runner.dryRun) {
      log.dry('sync API URL in $rel (${result.replacements} site(s))');
      return;
    }
    await File(path).writeAsString(result.text);
    log.ok(
      'synced ${config.web.serverUrlDefine} → '
      '${MobileApiUrlSync.apiForDefine(config.web.apiUrlNormalized)} in $rel '
      '(${result.replacements} site(s))',
    );
  }

  static String _apiForDefine(PodflyConfig config) =>
      MobileApiUrlSync.apiForDefine(config.web.apiUrlNormalized);

  static String generateGemfile() => '''
# Generated by podfly — Fastlane for Flutter mobile CI.
source "https://rubygems.org"

gem "fastlane", "~> 2.220"
''';

  static String generateAppfile(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final bundle = g.bundleId ?? 'com.example.app';
    final package = g.androidPackageName ?? 'com.example.app';
    return '''
# Generated by podfly — edit for your Apple / Play accounts.
# Prefer ENV in CI (see doc/github_actions_mobile.md).

app_identifier(ENV["APP_IDENTIFIER"] || "$bundle")
apple_id(ENV["APPLE_ID"] || "you@example.com") # Apple ID email
# team_id(ENV["TEAM_ID"] || "XXXXXXXXXX")
# itc_team_id(ENV["ITC_TEAM_ID"] || "XXXXXXXXXX")

# Android package name (Play)
json_key_file(ENV["PLAY_JSON_KEY_FILE"] || "") # path to service account JSON
package_name(ENV["PACKAGE_NAME"] || "$package")
''';
  }

  static String generateMatchfile(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final bundle = g.bundleId ?? 'com.example.app';
    return '''
# Generated by podfly — enable when using fastlane match for signing.
# https://docs.fastlane.tools/actions/match/

git_url(ENV["MATCH_GIT_URL"] || "git@github.com:YOUR_ORG/certificates.git")
storage_mode("git")
type("appstore") # appstore | development | adhoc
app_identifier([ENV["APP_IDENTIFIER"] || "$bundle"])
# username(ENV["APPLE_ID"])
# team_id(ENV["TEAM_ID"])
''';
  }

  /// Fastfile with build + release lanes. SERVER_URL from ENV (set in GHA).
  static String generateFastfile(PodflyConfig config) {
    final define = config.web.serverUrlDefine;
    return '''
# Generated by podfly — Fastlane lanes for Serverpod Flutter client.
#
# GHA sets $define (API URL) in the environment. Lanes pass it as
# --dart-define=$define=\$ENV.
#
# Release lanes need secrets (match / ASC / Play). Compile lanes do not.
# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md

def server_url_define
  ENV["$define"] || ENV["SERVER_URL"] || ""
end

def dart_defines
  url = server_url_define
  UI.user_error!("Set $define or SERVER_URL env (podfly web.api_url)") if url.empty?
  "--dart-define=$define=#{url}"
end

default_platform(:ios)

platform :ios do
  desc "Compile iOS (no codesign) — PR / smoke"
  lane :build do
    sh("flutter", "pub", "get")
    Dir.chdir("ios") { sh("pod", "install") }
    sh("flutter", "build", "ios", "--release", "--no-codesign", dart_defines)
  end

  desc "Signed IPA → TestFlight (needs match + ASC secrets)"
  lane :beta do
    setup_ci if ENV["CI"]

    # Uncomment when match repo + MATCH_* secrets are configured:
    # match(type: "appstore", readonly: is_ci)

    sh("flutter", "pub", "get")
    Dir.chdir("ios") { sh("pod", "install") }
    sh("flutter", "build", "ipa", "--release", dart_defines)

    ipa = Dir[File.expand_path("build/ios/ipa/*.ipa")].max_by { |f| File.mtime(f) }
    UI.user_error!("No IPA under build/ios/ipa") if ipa.nil?

    # Uncomment to upload (App Store Connect API key or Apple ID):
    # upload_to_testflight(ipa: ipa, skip_waiting_for_build_processing: true)
    UI.success("IPA ready: #{ipa} (enable upload_to_testflight when secrets are set)")
  end
end

platform :android do
  desc "Build App Bundle — PR / smoke"
  lane :build do
    sh("flutter", "pub", "get")
    sh("flutter", "build", "appbundle", "--release", dart_defines)
  end

  desc "App Bundle → Play internal track (needs Play JSON key)"
  lane :internal do
    sh("flutter", "pub", "get")
    sh("flutter", "build", "appbundle", "--release", dart_defines)

    aab = Dir[File.expand_path("build/app/outputs/bundle/release/*.aab")].first ||
          Dir[File.expand_path("build/app/outputs/**/*.aab")].max_by { |f| File.mtime(f) }
    UI.user_error!("No AAB found under build/app/outputs") if aab.nil?

    # Uncomment when PLAY_JSON_KEY_FILE / json_key is configured:
    # upload_to_play_store(
    #   track: "internal",
    #   aab: aab,
    #   release_status: "draft",
    # )
    UI.success("AAB ready: #{aab} (enable upload_to_play_store when secrets are set)")
  end
end
''';
  }

  /// Android workflow (ubuntu).
  static String generateAndroidWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    if (g.fastlane) return _androidFastlaneWorkflow(config);
    return _androidFlutterOnlyWorkflow(config);
  }

  /// iOS workflow (macos).
  static String generateIosWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    if (g.fastlane) return _iosFastlaneWorkflow(config);
    return _iosFlutterOnlyWorkflow(config);
  }

  static String _androidFlutterOnlyWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final api = _apiForDefine(config);
    final channel = g.flutterChannel;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — Flutter Android CI (compile only).');
    buf.writeln('# fastlane: false — set mobile.github_actions.fastlane: true for release lanes.');
    buf.writeln('# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md');
    buf.writeln();
    buf.writeln('name: Mobile Android');
    buf.writeln();
    _triggers(buf, flutterRel, g.androidWorkflow);
    buf.writeln('concurrency:');
    buf.writeln('  group: mobile-android-\${{ github.ref }}');
    buf.writeln('  cancel-in-progress: true');
    buf.writeln();
    buf.writeln('jobs:');
    buf.writeln('  appbundle:');
    buf.writeln('    name: flutter build appbundle');
    buf.writeln('    runs-on: ubuntu-latest');
    buf.writeln('    timeout-minutes: 45');
    buf.writeln('    permissions:');
    buf.writeln('      contents: read');
    buf.writeln();
    buf.writeln('    defaults:');
    buf.writeln('      run:');
    buf.writeln('        working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('    steps:');
    buf.writeln('      - name: Checkout');
    buf.writeln('        uses: actions/checkout@v4');
    buf.writeln();
    buf.writeln('      - name: Set up Java');
    buf.writeln('        uses: actions/setup-java@v4');
    buf.writeln('        with:');
    buf.writeln('          distribution: temurin');
    buf.writeln('          java-version: \'17\'');
    buf.writeln();
    buf.writeln('      - name: Set up Flutter');
    buf.writeln('        uses: subosito/flutter-action@v2');
    buf.writeln('        with:');
    buf.writeln('          channel: $channel');
    buf.writeln('          cache: true');
    buf.writeln();
    buf.writeln('      - name: Flutter pub get');
    buf.writeln('        run: flutter pub get');
    buf.writeln();
    buf.writeln('      - name: Build App Bundle');
    buf.writeln('        run: |');
    buf.writeln('          flutter build appbundle --release \\');
    buf.writeln(
        '            --dart-define=$define=$api');
    buf.writeln();
    buf.writeln('      - name: Upload AAB');
    buf.writeln('        uses: actions/upload-artifact@v4');
    buf.writeln('        with:');
    buf.writeln('          name: app-release-aab');
    buf.writeln('          path: $flutterRel/build/app/outputs/**/*.aab');
    buf.writeln('          if-no-files-found: error');
    buf.writeln();
    return buf.toString();
  }

  static String _iosFlutterOnlyWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final api = _apiForDefine(config);
    final channel = g.flutterChannel;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — Flutter iOS CI (compile only, --no-codesign).');
    buf.writeln('# fastlane: false — set mobile.github_actions.fastlane: true for TestFlight lane.');
    buf.writeln('# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md');
    buf.writeln();
    buf.writeln('name: Mobile iOS');
    buf.writeln();
    _triggers(buf, flutterRel, g.iosWorkflow);
    buf.writeln('concurrency:');
    buf.writeln('  group: mobile-ios-\${{ github.ref }}');
    buf.writeln('  cancel-in-progress: true');
    buf.writeln();
    buf.writeln('jobs:');
    buf.writeln('  ios:');
    buf.writeln('    name: flutter build ios');
    buf.writeln('    runs-on: macos-latest');
    buf.writeln('    timeout-minutes: 60');
    buf.writeln('    permissions:');
    buf.writeln('      contents: read');
    buf.writeln();
    buf.writeln('    defaults:');
    buf.writeln('      run:');
    buf.writeln('        working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('    steps:');
    buf.writeln('      - name: Checkout');
    buf.writeln('        uses: actions/checkout@v4');
    buf.writeln();
    buf.writeln('      - name: Set up Flutter');
    buf.writeln('        uses: subosito/flutter-action@v2');
    buf.writeln('        with:');
    buf.writeln('          channel: $channel');
    buf.writeln('          cache: true');
    buf.writeln();
    buf.writeln('      - name: Flutter pub get');
    buf.writeln('        run: flutter pub get');
    buf.writeln();
    buf.writeln('      - name: CocoaPods');
    buf.writeln('        run: |');
    buf.writeln('          cd ios');
    buf.writeln('          pod install');
    buf.writeln();
    buf.writeln('      - name: Build iOS (no codesign)');
    buf.writeln('        run: |');
    buf.writeln('          flutter build ios --release --no-codesign \\');
    buf.writeln('            --dart-define=$define=$api');
    buf.writeln();
    buf.writeln('      - name: Upload build (optional)');
    buf.writeln('        if: success()');
    buf.writeln('        uses: actions/upload-artifact@v4');
    buf.writeln('        with:');
    buf.writeln('          name: ios-release-unsigned');
    buf.writeln('          path: $flutterRel/build/ios/iphoneos');
    buf.writeln('          if-no-files-found: warn');
    buf.writeln();
    return buf.toString();
  }

  static String _androidFastlaneWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final api = _apiForDefine(config);
    final channel = g.flutterChannel;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — Android via Fastlane (GHA).');
    buf.writeln('#');
    buf.writeln('# Default lane: android internal (build AAB; Play upload commented');
    buf.writeln('# in Fastfile until PLAY_JSON_KEY_FILE secret is set).');
    buf.writeln('#');
    buf.writeln('# Input "lane": internal | build  (workflow_dispatch)');
    buf.writeln('# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md');
    buf.writeln();
    buf.writeln('name: Mobile Android');
    buf.writeln();
    buf.writeln('on:');
    buf.writeln('  workflow_dispatch:');
    buf.writeln('    inputs:');
    buf.writeln('      lane:');
    buf.writeln('        description: Fastlane lane (internal = release path, build = compile)');
    buf.writeln('        required: true');
    buf.writeln('        default: internal');
    buf.writeln('        type: choice');
    buf.writeln('        options: [internal, build]');
    buf.writeln('  push:');
    buf.writeln('    branches: [main]');
    buf.writeln('    paths:');
    buf.writeln('      - \'$flutterRel/**\'');
    buf.writeln('      - \'.github/workflows/${g.androidWorkflow}\'');
    buf.writeln();
    buf.writeln('concurrency:');
    buf.writeln('  group: mobile-android-\${{ github.ref }}');
    buf.writeln('  cancel-in-progress: true');
    buf.writeln();
    buf.writeln('jobs:');
    buf.writeln('  fastlane:');
    buf.writeln('    name: fastlane android');
    buf.writeln('    runs-on: ubuntu-latest');
    buf.writeln('    timeout-minutes: 45');
    buf.writeln('    permissions:');
    buf.writeln('      contents: read');
    buf.writeln();
    buf.writeln('    defaults:');
    buf.writeln('      run:');
    buf.writeln('        working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('    steps:');
    buf.writeln('      - name: Checkout');
    buf.writeln('        uses: actions/checkout@v4');
    buf.writeln();
    buf.writeln('      - name: Set up Java');
    buf.writeln('        uses: actions/setup-java@v4');
    buf.writeln('        with:');
    buf.writeln('          distribution: temurin');
    buf.writeln('          java-version: \'17\'');
    buf.writeln();
    buf.writeln('      - name: Set up Flutter');
    buf.writeln('        uses: subosito/flutter-action@v2');
    buf.writeln('        with:');
    buf.writeln('          channel: $channel');
    buf.writeln('          cache: true');
    buf.writeln();
    buf.writeln('      - name: Set up Ruby');
    buf.writeln('        uses: ruby/setup-ruby@v1');
    buf.writeln('        with:');
    buf.writeln('          ruby-version: \'3.2\'');
    buf.writeln('          bundler-cache: true');
    buf.writeln('          working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('      - name: Write Play JSON key (optional)');
    buf.writeln('        if: \${{ secrets.PLAY_JSON_KEY != \'\' }}');
    buf.writeln('        env:');
    buf.writeln('          PLAY_JSON_KEY: \${{ secrets.PLAY_JSON_KEY }}');
    buf.writeln('        run: |');
    buf.writeln('          echo "\$PLAY_JSON_KEY" > "\$RUNNER_TEMP/play-key.json"');
    buf.writeln('          echo "PLAY_JSON_KEY_FILE=\$RUNNER_TEMP/play-key.json" >> "\$GITHUB_ENV"');
    buf.writeln();
    buf.writeln('      - name: Fastlane');
    buf.writeln('        env:');
    buf.writeln(
        '          $define: $api  # ${MobileApiUrlSync.marker}');
    buf.writeln('          PACKAGE_NAME: \${{ secrets.PACKAGE_NAME }}');
    buf.writeln('        run: |');
    buf.writeln(
        '          # push: build (compile). workflow_dispatch can select internal.');
    buf.writeln('          LANE="\${{ github.event.inputs.lane || \'build\' }}"');
    buf.writeln('          bundle exec fastlane android "\$LANE"');
    buf.writeln();
    buf.writeln('      - name: Upload AAB');
    buf.writeln('        if: success()');
    buf.writeln('        uses: actions/upload-artifact@v4');
    buf.writeln('        with:');
    buf.writeln('          name: app-release-aab');
    buf.writeln('          path: $flutterRel/build/app/outputs/**/*.aab');
    buf.writeln('          if-no-files-found: warn');
    buf.writeln();
    return buf.toString();
  }

  static String _iosFastlaneWorkflow(PodflyConfig config) {
    final g = config.mobile.githubActionsOrDefault;
    final flutterRel = config.flutter.replaceAll(r'\', '/');
    final define = config.web.serverUrlDefine;
    final api = _apiForDefine(config);
    final channel = g.flutterChannel;
    final buf = StringBuffer();

    buf.writeln('# Generated by podfly — iOS via Fastlane (GHA).');
    buf.writeln('#');
    buf.writeln('# Default lane: ios beta (build IPA; TestFlight upload commented');
    buf.writeln('# in Fastfile until match + ASC secrets are configured).');
    buf.writeln('# Use lane "build" for --no-codesign compile only.');
    buf.writeln('#');
    buf.writeln('# Docs: https://github.com/127thousand/podfly/blob/main/doc/github_actions_mobile.md');
    buf.writeln();
    buf.writeln('name: Mobile iOS');
    buf.writeln();
    buf.writeln('on:');
    buf.writeln('  workflow_dispatch:');
    buf.writeln('    inputs:');
    buf.writeln('      lane:');
    buf.writeln('        description: Fastlane lane (beta = release path, build = no codesign)');
    buf.writeln('        required: true');
    buf.writeln('        default: beta');
    buf.writeln('        type: choice');
    buf.writeln('        options: [beta, build]');
    buf.writeln('  push:');
    buf.writeln('    branches: [main]');
    buf.writeln('    paths:');
    buf.writeln('      - \'$flutterRel/**\'');
    buf.writeln('      - \'.github/workflows/${g.iosWorkflow}\'');
    buf.writeln();
    buf.writeln('concurrency:');
    buf.writeln('  group: mobile-ios-\${{ github.ref }}');
    buf.writeln('  cancel-in-progress: true');
    buf.writeln();
    buf.writeln('jobs:');
    buf.writeln('  fastlane:');
    buf.writeln('    name: fastlane ios');
    buf.writeln('    runs-on: macos-latest');
    buf.writeln('    timeout-minutes: 75');
    buf.writeln('    permissions:');
    buf.writeln('      contents: read');
    buf.writeln();
    buf.writeln('    defaults:');
    buf.writeln('      run:');
    buf.writeln('        working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('    steps:');
    buf.writeln('      - name: Checkout');
    buf.writeln('        uses: actions/checkout@v4');
    buf.writeln();
    buf.writeln('      - name: Set up Flutter');
    buf.writeln('        uses: subosito/flutter-action@v2');
    buf.writeln('        with:');
    buf.writeln('          channel: $channel');
    buf.writeln('          cache: true');
    buf.writeln();
    buf.writeln('      - name: Set up Ruby');
    buf.writeln('        uses: ruby/setup-ruby@v1');
    buf.writeln('        with:');
    buf.writeln('          ruby-version: \'3.2\'');
    buf.writeln('          bundler-cache: true');
    buf.writeln('          working-directory: $flutterRel');
    buf.writeln();
    buf.writeln('      - name: Fastlane');
    buf.writeln('        env:');
    buf.writeln(
        '          $define: $api  # ${MobileApiUrlSync.marker}');
    buf.writeln('          MATCH_PASSWORD: \${{ secrets.MATCH_PASSWORD }}');
    buf.writeln('          MATCH_GIT_URL: \${{ secrets.MATCH_GIT_URL }}');
    buf.writeln('          MATCH_GIT_BASIC_AUTHORIZATION: \${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}');
    buf.writeln('          APP_IDENTIFIER: \${{ secrets.APP_IDENTIFIER }}');
    buf.writeln('          APPLE_ID: \${{ secrets.APPLE_ID }}');
    buf.writeln('          TEAM_ID: \${{ secrets.TEAM_ID }}');
    buf.writeln('          ITC_TEAM_ID: \${{ secrets.ITC_TEAM_ID }}');
    buf.writeln('          APP_STORE_CONNECT_API_KEY_KEY_ID: \${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}');
    buf.writeln('          APP_STORE_CONNECT_API_KEY_ISSUER_ID: \${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}');
    buf.writeln('          APP_STORE_CONNECT_API_KEY_KEY: \${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}');
    buf.writeln('        run: |');
    buf.writeln(
        '          # push: build (no codesign). workflow_dispatch can select beta.');
    buf.writeln('          LANE="\${{ github.event.inputs.lane || \'build\' }}"');
    buf.writeln('          bundle exec fastlane ios "\$LANE"');
    buf.writeln();
    buf.writeln('      - name: Upload IPA');
    buf.writeln('        if: success()');
    buf.writeln('        uses: actions/upload-artifact@v4');
    buf.writeln('        with:');
    buf.writeln('          name: ios-ipa');
    buf.writeln('          path: $flutterRel/build/ios/ipa/*.ipa');
    buf.writeln('          if-no-files-found: warn');
    buf.writeln();
    return buf.toString();
  }

  static void _triggers(StringBuffer buf, String flutterRel, String workflowFile) {
    buf.writeln('on:');
    buf.writeln('  workflow_dispatch:');
    buf.writeln('  push:');
    buf.writeln('    branches: [main]');
    buf.writeln('    paths:');
    buf.writeln('      - \'$flutterRel/**\'');
    buf.writeln('      - \'.github/workflows/$workflowFile\'');
    buf.writeln();
  }
}
